services:
  redis:
    image: redis:7
    container_name: redis-catalog
    ports:
      - "6379:6379"
    restart: unless-stopped
  postgres:
    image: postgres:15
    container_name: postgres-catalog
    environment:
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      POSTGRES_DB: catalog
    ports:
      - "5432:5432"
    restart: unless-stopped